/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Actor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Actor__factory>;
    getContractFactory(
      name: "ActorFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ActorFactory__factory>;
    getContractFactory(
      name: "Counter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Counter__factory>;
    getContractFactory(
      name: "InfiniteLoop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InfiniteLoop__factory>;
    getContractFactory(
      name: "IL1MsgVerify",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IL1MsgVerify__factory>;

    getContractAt(
      name: "Actor",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Actor>;
    getContractAt(
      name: "ActorFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ActorFactory>;
    getContractAt(
      name: "Counter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Counter>;
    getContractAt(
      name: "InfiniteLoop",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InfiniteLoop>;
    getContractAt(
      name: "IL1MsgVerify",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IL1MsgVerify>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
